### PR TITLE
Interactive branch

### PR DESCRIPTION
**Pull request by deikdesign**
- You can add tasks by clicking enter
- You can delete tasks by selecting and then delete list
- You can delete all selected tasks
- The status is updated

### CODE REVIEW

**Review by o-rashad — APPROVED** [review]
Asslam Alaikum @deikdesign  ,😊

Hi👋🏽, Your project is complete!  There is nothing else to say other than... it's time to merge it 😎 

# Congratulations! 🎉 

Happy coding!👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by o-rashad** [comment]
Hey @deikdesign, 

Your project have been accepted on the requirements of the `To Do list: list structure` project.

for `To Do list: interactive list` project, please open a new pull request for it.

and submit a new code review for the `interactive list` project. 

#### Please make sure you submitted the right pull request for the corresponding project

**Comment by mikethreels** [comment]
Hi Dean, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

As the previous reviewer mentioned please open a new PR for the interactive list milestone

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by EricMbouwe — COMMENTED** [review]
### Hi @deikdesign, 

# Status: Approved ✔️
Excellent job on this project. Keep it up 👏
Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by enniopo** [comment]
Hi @deikdesign, well done on your progress 👏 
I am reaching out because we noticed that Webpack is not set up correctly. 
Please try to fix it, if you have time. 

Thank you 
Ennio

**Pull request merged**
